name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18
      
      - name: Build
        shell: bash
        run: |
          npm install

          if [ "$RUNNER_OS" == "Linux" ]; then
            npm run build-linux
            mv OpenPassy-linux-x64.zip OpenPassy-Linux-x64.zip
          elif [ "$RUNNER_OS" == "Windows" ]; then
            npm run build-win
            mv OpenPassy-win32-x64.zip OpenPassy-Windows-x64.zip
          elif [ "$RUNNER_OS" == "macOS" ]; then
            npm run build-mac
            mv OpenPassy-darwin-x64.zip OpenPassy-macOS-x64.zip
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}
          path: ${{ format('OpenPassy-{0}-x64.zip', runner.os) }}